# Generated by Django 5.1.5 on 2025-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fosterer_status',
            field=models.CharField(choices=[('none', 'None'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('staff', 'Staff'), ('admin', 'Admin')], default='simple', max_length=10),
        ),
    ]
