# Generated by Django 5.1.5 on 2025-03-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_fosterer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealPetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('character_traits', models.TextField(blank=True, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_pet_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
