# Generated by Django 5.1.5 on 2025-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_idealpetprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealpetprofile',
            name='breed',
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='cat_breed',
            field=models.CharField(blank=True, choices=[('persian', 'Persian'), ('siamese', 'Siamese'), ('maine_coon', 'Maine Coon'), ('bengal', 'Bengal'), ('ragdoll', 'Ragdoll'), ('sphynx', 'Sphynx'), ('british_shorthair', 'British Shorthair'), ('scottish_fold', 'Scottish Fold'), ('abyssinian', 'Abyssinian'), ('burmese', 'Burmese'), ('oriental', 'Oriental'), ('american_shorthair', 'American Shorthair'), ('russian_blue', 'Russian Blue'), ('norwegian_forest', 'Norwegian Forest Cat'), ('savannah', 'Savannah'), ('tonkinese', 'Tonkinese'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='dog_breed',
            field=models.CharField(blank=True, choices=[('chihuahua', 'Chihuahua'), ('labrador', 'Labrador Retriever'), ('beagle', 'Beagle'), ('husky', 'Siberian Husky'), ('poodle', 'Poodle'), ('bulldog', 'Bulldog'), ('golden_retriever', 'Golden Retriever'), ('german_shepherd', 'German Shepherd'), ('dachshund', 'Dachshund'), ('rottweiler', 'Rottweiler'), ('pomeranian', 'Pomeranian'), ('shih_tzu', 'Shih Tzu'), ('doberman', 'Doberman'), ('boxer', 'Boxer'), ('great_dane', 'Great Dane'), ('border_collie', 'Border Collie'), ('corgi', 'Corgi'), ('pug', 'Pug'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
