# Generated by Django 5.1.5 on 2025-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_idealpetprofile_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealpetprofile',
            name='age',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50),
        ),
        migrations.AlterField(
            model_name='idealpetprofile',
            name='character_traits',
            field=models.CharField(blank=True, choices=[('cute', 'Cute'), ('playful', 'Playful'), ('energetic', 'Energetic'), ('lazy', 'Lazy'), ('friendly', 'Friendly'), ('adventurous', 'Adventurous'), ('glutton', 'Glutton'), ('shy', 'Shy'), ('social', 'Social')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idealpetprofile',
            name='disabilities',
            field=models.CharField(blank=True, choices=[('with', 'With'), ('without', 'Without')], max_length=50, null=True),
        ),
    ]
