# Generated by Django 5.1.5 on 2025-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_idealpetprofile_age_idealpetprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealpetprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50),
        ),
    ]
