# Generated by Django 5.1.5 on 2025-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_petprofile_fur'),
        ('users', '0007_remove_idealpetprofile_age_idealpetprofile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealpetprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='pets.allergy'),
        ),
        migrations.RemoveField(
            model_name='idealpetprofile',
            name='character_traits',
        ),
        migrations.RemoveField(
            model_name='idealpetprofile',
            name='disabilities',
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='character_traits',
            field=models.ManyToManyField(blank=True, to='pets.charactertrait'),
        ),
        migrations.AddField(
            model_name='idealpetprofile',
            name='disabilities',
            field=models.ManyToManyField(blank=True, to='pets.disability'),
        ),
    ]
