# Generated by Django 5.1.5 on 2025-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_idealpetprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealpetprofile',
            name='fur',
            field=models.CharField(blank=True, choices=[('Hairless', 'Hairless'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=10, null=True),
        ),
    ]
