# Generated by Django 5.1.5 on 2025-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_idealpetprofile_fur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealpetprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idealpetprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True),
        ),
    ]
