# Generated by Django 5.1.5 on 2025-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile_photo_fosteringapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosteringapplication',
            name='first_name',
            field=models.CharField(default='n/a', max_length=150),
        ),
        migrations.AddField(
            model_name='fosteringapplication',
            name='last_name',
            field=models.CharField(default='n/a', max_length=150),
        ),
    ]
