# Generated by Django 5.1.5 on 2025-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_petprofile_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
