# Generated by Django 5.1.5 on 2025-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_petprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Dog', max_length=10),
        ),
    ]
