# Generated by Django 5.1.5 on 2025-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petprofile_image_alter_petprofile_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pet_photos/'),
        ),
    ]
