# Generated by Django 5.1.5 on 2025-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/pet_photos/'),
        ),
    ]
