# Generated by Django 5.1.5 on 2025-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_petprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
