# Generated by Django 5.1.5 on 2025-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_petprofile_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=50),
        ),
    ]
