# Generated by Django 5.1.5 on 2025-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_petprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50),
        ),
    ]
