# Generated by Django 5.1.5 on 2025-03-30 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_rename_favorite_favoritedpets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritedPets',
            new_name='FavoritedPet',
        ),
    ]
