# Generated by Django 5.1.5 on 2025-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_rename_favoritedpets_favoritedpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='character_traits',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='character_traits',
            field=models.ManyToManyField(blank=True, to='pets.charactertrait'),
        ),
    ]
