# Generated by Django 5.1.5 on 2025-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_charactertrait_remove_petprofile_character_traits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='allergies',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='pets.allergies'),
        ),
    ]
