# Generated by Django 5.1.5 on 2025-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_allergies_remove_petprofile_allergies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergies',
            new_name='Allergie',
        ),
    ]
