# Generated by Django 5.1.5 on 2025-04-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_rename_allergies_allergie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergie',
            new_name='Allergies',
        ),
    ]
