# Generated by Django 5.1.5 on 2025-04-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_rename_allergie_allergies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergies',
            new_name='Allergy',
        ),
    ]
