# Generated by Django 5.1.5 on 2025-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_disability_remove_petprofile_disabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='fur',
            field=models.CharField(blank=True, choices=[('Hairless', 'Hairless'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=50),
        ),
    ]
