# Generated by Django 5.1.5 on 2025-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_petprofile_fur'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='shelter_arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
