# Generated by Django 5.1.5 on 2025-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_petprofile_shelter_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='image',
            field=models.ImageField(default='pet_photos/default_pet.jpg', upload_to='pet_photos/'),
        ),
    ]
